export const TEST_TYPE = 'TEST_TYPE';
export const TEST_SUCCESS = 'TEST_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SET_SIDE_BAR = 'SET_SIDE_BAR';

// users
export const GET_USERS_DEFINITION = 'GET_USERS_DEFINITION';
export const GET_USERS_DEFINITION_SUCCESS = 'GET_USERS_DEFINITION_SUCCESS';
export const GET_USERS_DEFINITION_FAILED = 'GET_USERS_DEFINITION_FAILED';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

// table
export const FETCH_TABLE_DEFINITION = 'FETCH_TABLE_DEFINITION';
export const FETCH_TABLE_DEFINITION_SUCCESS = 'FETCH_TABLE_DEFINITION_SUCCESS';
export const FETCH_TABLE_DEFINITION_FAILED = 'FETCH_TABLE_DEFINITION_FAILED';
export const FETCH_TABLE_DATA = 'FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const FETCH_TABLE_DATA_FAILED = 'FETCH_TABLE_DATA_FAILED';
export const UPDATE_TABLE_ROW = 'UPDATE_TABLE_ROW';
export const UPDATE_TABLE_ROW_SUCCESS = 'UPDATE_TABLE_ROW_SUCCESS';
export const UPDATE_TABLE_ROW_FAILED = 'UPDATE_TABLE_ROW_FAILED';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';
export const DELETE_TABLE_ROW_SUCCESS = 'DELETE_TABLE_ROW_SUCCESS';
export const DELETE_TABLE_ROW_FAILED = 'DELETE_TABLE_ROW_FAILED';
export const ADD_TABLE_ROW = 'ADD_TABLE_ROW';
export const ADD_TABLE_ROW_SUCCESS = 'ADD_TABLE_ROW_SUCCESS';
export const ADD_TABLE_ROW_FAILED = 'ADD_TABLE_ROW_FAILED';
export const SEARCH_IN_TABLE = 'SEARCH_IN_TABLE';
export const SEARCH_IN_TABLE_SUCCESS = 'SEARCH_IN_TABLE_SUCCESS';
export const SEARCH_IN_TABLE_FAILED = 'SEARCH_IN_TABLE_FAILED';

// modal
//Modal
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_GENERIC_ERROR_MODAL = 'SHOW_GENERIC_ERROR_MODAL';