export const TEST_TYPE = 'TEST_TYPE';
export const TEST_SUCCESS = 'TEST_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SET_SIDE_BAR = 'SET_SIDE_BAR';

// users
export const GET_USERS_DEFINITION = 'GET_USERS_DEFINITION';
export const GET_USERS_DEFINITION_SUCCESS = 'GET_USERS_DEFINITION_SUCCESS';
export const GET_USERS_DEFINITION_FAILED = 'GET_USERS_DEFINITION_FAILED';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
